kind: pipeline
type: docker
name: default

steps:
  - name: sonar_analysis
    image: gradle:jdk21
    commands:
      - cd /drone/src/nexus-agency-system/backend
      - ./gradlew sonar
    when:
      branch:
        - "Carlos'Main"
        - "Carlos'QA"
        - "Carlos'Dev"

  - name: stop_and_redeploy_frontend
    image: docker
    commands:
      - cd /drone/src/nexus-agency-system/frontend
      - docker stop nexusfront || true
      - docker rm nexusfront || true
      - docker run -d --name nexusfront nexusfront
    when:
      branch:
        - "Carlos'Main"
        - "Carlos'QA"
        - "Carlos'Dev"

trigger:
  event:
    - push
    - pull_request
