services:
  nexus:
    build: .
    image: nexus-app:prod
    container_name: nexus-prod
    env_file: .env.prod
    ports:
      - "8083:8080"
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: nexus-db-prod
    environment:
      MYSQL_DATABASE: nexus_prod
      MYSQL_USER: nexus
      MYSQL_PASSWORD: nexus
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - nexus-prod-db:/var/lib/mysql

volumes:
  nexus-prod-db:
