-- Usuarios (schemas) por ambiente
-- Nota: en Oracle, el schema es el propio usuario.

ALTER SESSION SET "_ORACLE_SCRIPT"=true;

CREATE USER NEXUS_DEV IDENTIFIED BY dev_pwd DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE, CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW TO NEXUS_DEV;

CREATE USER NEXUS_UAT IDENTIFIED BY uat_pwd DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE, CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW TO NEXUS_UAT;

CREATE USER NEXUS_PROD IDENTIFIED BY prod_pwd DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE, CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW TO NEXUS_PROD;