FROM jenkins/jenkins:lts

USER root
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      ca-certificates curl gnupg lsb-release \
      docker.io docker-compose-plugin && \
    rm -rf /var/lib/apt/lists/*

# Permitir que el usuario jenkins use el socket remoto del daemon (vía DOCKER_HOST)
RUN usermod -aG docker jenkins

USER jenkins