services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    image: jenkins-with-docker:lts
    container_name: jenkins
    user: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - DOCKER_HOST=tcp://dind:2375
      # usuario/clave admin usados por el groovy init
      - JENKINS_ADMIN_ID=${JENKINS_ADMIN_ID}
      - JENKINS_ADMIN_PASSWORD=${JENKINS_ADMIN_PASSWORD}
    volumes:
      - jenkins_home:/var/jenkins_home
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - dind
    restart: unless-stopped

  dind:
    image: docker:24.0-dind
    container_name: dind
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=
    ports:
      - "2375:2375"
    command: ["--host=tcp://0.0.0.0:2375", "--mtu=1450"]
    volumes:
      - dind_storage:/var/lib/docker
    restart: unless-stopped

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    depends_on:
      - sonar-db
    ports:
      - "9000:9000"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonar-db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=${SONAR_DB_USER}
      - SONARQUBE_JDBC_PASSWORD=${SONAR_DB_PASS}
      - SONAR_WEB_JAVAOPTS=-Xmx1g -Xms1g
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    restart: unless-stopped

  sonar-db:
    image: postgres:15
    container_name: sonar-db
    environment:
      - POSTGRES_USER=${SONAR_DB_USER}
      - POSTGRES_PASSWORD=${SONAR_DB_PASS}
      - POSTGRES_DB=sonar
    volumes:
      - sonar_db:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  jenkins_home:
  sonarqube_logs:      
  dind_storage:
  sonarqube_data:
  sonarqube_extensions:
  sonar_db: