FROM jenkins/jenkins:lts

USER root

# Base deps (you already had these)
RUN apt-get update && apt-get install -y --no-install-recommends \
     ca-certificates curl gnupg lsb-release \
     && rm -rf /var/lib/apt/lists/* \
     && install -m 0755 -d /etc/apt/keyrings \
     && curl -fsSL https://download.docker.com/linux/debian/gpg \
     | gpg --dearmor -o /etc/apt/keyrings/docker.gpg \
     && chmod a+r /etc/apt/keyrings/docker.gpg \
     && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
     https://download.docker.com/linux/debian bookworm stable" \
     > /etc/apt/sources.list.d/docker.list \
     && apt-get update \
     && apt-get install -y --no-install-recommends \
     docker-buildx-plugin docker-ce-cli docker-compose-plugin \
     && rm -rf /var/lib/apt/lists/* \
     getent group docker || groupadd docker \
     && usermod -aG docker jenkins

USER jenkins
